name = "ReactiveECS"
uuid = "98e33af6-2ee5-5afd-9e75-cbc738b765c9"
authors = ["Kaptue Talom Lael <gesee37@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FieldViews = "ff5a1669-b1f2-423e-bbd7-b7fa0f7e0224"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
FieldViews = "0.3"
Reexport = "1.2"
StructArrays = "0.7"
julia = "1.10"
